name = "HestiaUtils"
uuid = "3f427d17-6377-4d41-bf72-61d89616e759"
authors = ["Moorits Mihkel Muru <mmuru@aip.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
